spring.application.name=authorization-server

spring.datasource.url=jdbc:postgresql://localhost:5432/db_test
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/authorizationServer
server.port=8080
server.servlet.context-path=/authorizationServer

